#!/bin/bash

## this is a skeleton I am making as I work through the steps manually; to be actually written later
## helpful information:
## https://blockofcode.wordpress.com/2009/02/09/making-a-theme-for-xfwm4/

## ====== fix images generated by GIMP

## move customized images into own directory
# mkdir active && cp *-active.xpm active/
# cd active

## Find and replace the color definition headers in images
## Note: Verify the charecters are the same in each, as GIMP will reassign them. Change the 2nd to match the first
	## FIND: (in plain text)
	# " 	c #000000",
	# ".	c #0000EE",
	# "+	c #000088",
	# "@	c #000044",
	# "#	c #FFFFFF",
		## FIND (same as above, but regex compliant):
		# "\s+c #000000",
		# "\.\s+c #0000EE",
		# "\+\s+c #000088",
		# "\@\s+c #000044",
		# "\#\s+c #FFFFFF",
		## FIND (same as above, but only required bits):
		# #000000"
		# #0000EE"
		# #000088"
		# #000044"
		# #FFFFFF"
	##
	## REPLACE WITH (in plain text) ->
	# " 	c #000000",
	# ".	c #0000EE s active_hilight_1",
	# "+	c #000088 s active_color_1",
	# "@	c #000044 s active_shadow_1",
	# "#	c #FFFFFF s active_text_color",
		## REPLACE (same as above, but regex compliant):
		# "\ \tc #000000",
		# "\.\tc #0000EE s active_hilight_1",
		# "\+\tc #000088 s active_color_1",
		# "\@\tc #000044 s active_shadow_1",
		# "\#\tc #FFFFFF s active_text_color",
		## REPLACE (same as above, but only required bits):
		# #000000",
		# #0000EE s active_hilight_1"
		# #000088 s active_color_1"
		# #000044 s active_shadow_1"
		# #FFFFFF s active_text_color"

## WORKS:
sed -i -e 's/#0000EE"/#0000EE s active_hilight_1"/g' *-active.xpm
## WORKS:
sed -i -e \
's/#0000EE"/#0000EE s active_hilight_1"/g' \
*-active.xpm

sed -i \
-e 's/#0000EE"/#0000EE s active_hilight_1"/g' \
-e 's/#0000EE"/#0000EE s active_hilight_1"/g' \
*-active.xpm

sed -i -e \
-e 's/c #5080D0"/c #5080D0 s active_color_1"/g' \
-e 's/FIND/REPLACE/g' \

## *	must leave trailing double quote to prevent the operation
## 		accidentaly being run more than once on the same line; the
## 		double quote indicates the *definate* end of the line
## 	*	must leave the -e at start of each line; it won't work if
##		put into the main command only once
sed -i \
-e 's/FIND"/REPLACE"/g' \
-e 's/#0000EE"/#0000EE s active_hilight_1"/g' \
-e 's/#000088"/#000088 s active_color_1""/g' \
-e 's/#000044"/#000044 s active_shadow_1""/g' \
-e 's/#FFFFFF"/#FFFFFF s active_text_color""/g' \
*-active.xpm








######################
## create temporary working directory "inactive"

## ~~copy all files *-active.xpm" into diretcory "inactive"~~

## ~~rename all files in "inactive" to *-inactive.xpm~~

## Find replace in files:
	## _active_xpm
	## ->
	## _inactive_xpm








